sudo: false
language: python

python:
    - 3.4
    - 3.5
    - 3.6

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required

install:
    - pip install tox

script:
    - tox -e py

cache:
    - pip

notifications:
  email: false
